// TMIPlanEditorView.swift
// TMI
//
// Unified editor for creating and editing TMI plans using accordion sections.
// - Create mode: existingPlan == nil, optionally pre-select a student via preselectedStudent
// - Edit mode:   existingPlan != nil, pre-populates all fields on appear
//

import SwiftUI
import FirebaseAuth

// MARK: - TMIPlanEditorView

struct TMIPlanEditorView: View {
    @Environment(\.dismiss) private var dismiss

    // MARK: - Configuration

    let existingPlan: TMIPlan?
    let preselectedStudent: Student?

    /// Called after a plan is successfully created or updated.
    let onSaved: ((TMIPlan) -> Void)?

    /// Backward-compat shim — called on create success (no plan object).
    let onPlanCreated: (() -> Void)?

    // MARK: - Computed mode

    private var isEditMode: Bool { existingPlan != nil }

    // MARK: - Accordion expansion

    @State private var detailsExpanded: Bool = true
    @State private var studentsExpanded: Bool = false
    @State private var interestsExpanded: Bool = false
    @State private var careersExpanded: Bool = false
    @State private var resourcesExpanded: Bool = false
    @State private var formsExpanded: Bool = false
    @State private var goalsExpanded: Bool = false
    @State private var approvalExpanded: Bool = false
    @State private var advancedSectionsExpanded: Bool = false

    // MARK: - Plan Details state

    @State private var planTitle: String = ""
    @State private var planDescription: String = ""
    @State private var selectedModel: TMIPlanModel = .chaseYourSpace
    @State private var startDate: Date = Date()
    @State private var endDate: Date? = nil
    @State private var hasEndDate: Bool = false

    // MARK: - Students state

    @State private var selectedStudents: [Student] = []
    @State private var availableStudents: [Student] = []
    @State private var isLoadingStudents: Bool = false
    @State private var showStudentPicker: Bool = false

    // MARK: - Linked data state (section components)

    @State private var linkedInterests: [Interest] = []
    @State private var linkedCareers: [Career] = []
    @State private var linkedResources: [Resource] = []

    // MARK: - Goals state

    @State private var goals: [Goal] = []
    @State private var notes: String = ""
    @State private var studentNextStep: String = ""
    @State private var showAddGoal: Bool = false
    @State private var newGoalDescription: String = ""
    @State private var newGoalDueDate: Date? = nil
    @State private var newGoalHasDueDate: Bool = false

    // MARK: - Approval state

    @State private var approvalStatus: PlanApprovalStatus = .draft
    @State private var approvalHistory: [ApprovalHistoryEntry] = []

    // MARK: - Async / save state

    @State private var isSaving: Bool = false
    @State private var errorMessage: String?
    @State private var didPopulate: Bool = false

    // MARK: - Services

    private let planService = TMIPlanService.shared
    private let studentService = StudentService.shared

    // MARK: - Validation

    private var isValid: Bool {
        !planTitle.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty &&
        !selectedStudents.isEmpty &&
        !trimmedStudentNextStep.isEmpty
    }

    // MARK: - Auto-generated title

    private var autoGeneratedTitle: String {
        Self.defaultPlanTitle(for: selectedModel, students: selectedStudents)
    }

    private var trimmedStudentNextStep: String {
        studentNextStep.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - Init

    init(
        existingPlan: TMIPlan? = nil,
        preselectedStudent: Student? = nil,
        onSaved: ((TMIPlan) -> Void)? = nil,
        onPlanCreated: (() -> Void)? = nil
    ) {
        self.existingPlan = existingPlan
        self.preselectedStudent = preselectedStudent
        self.onSaved = onSaved
        self.onPlanCreated = onPlanCreated
    }

    // MARK: - Body

    var body: some View {
        ZStack {
            TMIBackgroundView(variant: .plans)
                .ignoresSafeArea()

            ScrollView {
                VStack(spacing: TMISpacing.sm) {
                    // 1. Plan Details
                    sectionCard {
                        AccordionSection(
                            icon: "doc.text.fill",
                            title: "Plan Details",
                            badge: planTitle.isEmpty ? nil : "Set",
                            badgeColor: .tmiPrimary,
                            isRequired: true,
                            isExpanded: $detailsExpanded
                        ) {
                            planDetailsContent
                        }
                    }

                    // 2. Students
                    sectionCard {
                        AccordionSection(
                            icon: "person.2.fill",
                            title: "Students",
                            badge: selectedStudents.isEmpty ? nil : "\(selectedStudents.count)",
                            badgeColor: .tmiPrimary,
                            isRequired: true,
                            isExpanded: $studentsExpanded
                        ) {
                            studentsContent
                        }
                    }

                    // 3. Interests & Hobbies
                    sectionCard {
                        AccordionSection(
                            icon: "heart.fill",
                            title: "Interests & Hobbies",
                            badge: linkedInterests.isEmpty ? nil : "\(linkedInterests.count)",
                            badgeColor: .pink,
                            isExpanded: $interestsExpanded
                        ) {
                            PlanInterestsSection(
                                linkedInterests: $linkedInterests,
                                students: selectedStudents
                            )
                        }
                    }

                    // 4. Resources
                    sectionCard {
                        AccordionSection(
                            icon: "book.fill",
                            title: "Resources",
                            badge: linkedResources.isEmpty ? nil : "\(linkedResources.count)",
                            badgeColor: .orange,
                            isExpanded: $resourcesExpanded
                        ) {
                            PlanResourcesSection(
                                linkedResources: $linkedResources,
                                students: selectedStudents
                            )
                        }
                    }

                    advancedPlanningCard

                    if advancedSectionsExpanded {
                        // 5. Career Pathways
                        sectionCard {
                            AccordionSection(
                                icon: "briefcase.fill",
                                title: "Career Pathways",
                                badge: linkedCareers.isEmpty ? nil : "\(linkedCareers.count)",
                                badgeColor: .purple,
                                isExpanded: $careersExpanded
                            ) {
                                PlanCareersSection(
                                    linkedCareers: $linkedCareers,
                                    students: selectedStudents,
                                    linkedInterests: linkedInterests
                                )
                            }
                        }

                        // 6. Forms & Surveys
                        sectionCard {
                            AccordionSection(
                                icon: "checklist",
                                title: "Forms & Surveys",
                                isExpanded: $formsExpanded
                            ) {
                                PlanFormsSection(planId: existingPlan?.id)
                            }
                        }

                        // 7. Goals & Progress
                        sectionCard {
                            AccordionSection(
                                icon: "flag.fill",
                                title: "Goals & Progress",
                                badge: goals.isEmpty ? nil : "\(goals.count)",
                                badgeColor: .green,
                                isExpanded: $goalsExpanded
                            ) {
                                goalsContent
                            }
                        }

                        // 8. Approval
                        sectionCard {
                            AccordionSection(
                                icon: approvalStatus.icon,
                                title: "Approval",
                                badge: approvalStatus.displayName,
                                badgeColor: approvalStatusColor(approvalStatus),
                                isExpanded: $approvalExpanded
                            ) {
                                approvalContent
                            }
                        }
                    }

                    if let errorMessage {
                        Text(errorMessage)
                            .font(.tmiCaption)
                            .foregroundStyle(Color.tmiError)
                            .padding(TMISpacing.md)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .background(Color.tmiError.opacity(0.1))
                            .cornerRadius(TMIRadius.sm)
                            .padding(.horizontal, TMISpacing.screenPadding)
                    }

                    Spacer(minLength: 100)
                }
                .padding(.top, TMISpacing.md)
            }

            bottomSaveBar
        }
        .navigationTitle(isEditMode ? "Edit Plan" : "New TMI Plan")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .topBarLeading) {
                Button("Cancel") { dismiss() }
            }
        }
        .sheet(isPresented: $showStudentPicker) {
            studentPickerSheet
                .tmiSheetStyle()
        }
        .sheet(isPresented: $showAddGoal) {
            addGoalSheet
                .tmiSheetStyle()
        }
        .task {
            await loadAvailableStudents()
        }
        .onAppear {
            guard !didPopulate else { return }
            didPopulate = true
            populateFields()
        }
        .onChange(of: selectedModel) { _, _ in autoUpdateTitle() }
        .onChange(of: selectedStudents) { _, _ in autoUpdateTitle() }
    }

    // MARK: - Section Card

    @ViewBuilder
    private func sectionCard<C: View>(@ViewBuilder _ content: () -> C) -> some View {
        content()
            .background(Color.tmiSurface)
            .cornerRadius(TMIRadius.md)
            .shadow(color: .black.opacity(0.05), radius: 4, x: 0, y: 2)
            .padding(.horizontal, TMISpacing.screenPadding)
    }

    // MARK: - Plan Details Content

    private var planDetailsContent: some View {
        VStack(alignment: .leading, spacing: TMISpacing.md) {
            // Title
            fieldGroup(label: "Plan Title") {
                TextField(
                    "",
                    text: $planTitle,
                    prompt: Text("Enter plan title").foregroundColor(.tmiTextTertiary)
                )
                .font(.tmiBody)
                .foregroundStyle(Color.tmiTextPrimary)
                .padding(TMISpacing.md)
                .background(Color.tmiBackground)
                .cornerRadius(TMIRadius.sm)
            }

            Divider()

            // Model grid
            fieldGroup(label: "TMI Model") {
                LazyVGrid(
                    columns: [GridItem(.flexible()), GridItem(.flexible())],
                    spacing: TMISpacing.sm
                ) {
                    ForEach(TMIPlanModel.allCases, id: \.self) { model in
                        modelCard(model)
                    }
                }
            }

            Divider()

            // Description
            fieldGroup(label: "Description (Optional)") {
                TextEditor(text: $planDescription)
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextPrimary)
                    .frame(minHeight: 80)
                    .padding(TMISpacing.sm)
                    .background(Color.tmiBackground)
                    .cornerRadius(TMIRadius.sm)
            }

            Divider()

            // Dates
            DatePicker("Start Date", selection: $startDate, displayedComponents: .date)
                .font(.tmiBody)
                .foregroundStyle(Color.tmiTextPrimary)

            Toggle("Set End Date", isOn: $hasEndDate)
                .font(.tmiBody)
                .foregroundStyle(Color.tmiTextPrimary)

            if hasEndDate {
                DatePicker(
                    "End Date",
                    selection: Binding(
                        get: { endDate ?? startDate },
                        set: { endDate = $0 }
                    ),
                    in: startDate...,
                    displayedComponents: .date
                )
                .font(.tmiBody)
                .foregroundStyle(Color.tmiTextPrimary)
            }
        }
    }

    private func modelCard(_ model: TMIPlanModel) -> some View {
        let modelColor = colorForModel(model)
        let isSelected = selectedModel == model

        return Button {
            selectedModel = model
        } label: {
            VStack(spacing: 8) {
                ZStack {
                    Circle()
                        .fill(modelColor.opacity(isSelected ? 0.25 : 0.12))
                        .frame(width: 40, height: 40)
                    Image(systemName: iconForModel(model))
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundStyle(modelColor)
                }

                Text(model.rawValue)
                    .font(.caption)
                    .fontWeight(isSelected ? .semibold : .regular)
                    .foregroundStyle(isSelected ? modelColor : Color.tmiTextPrimary)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .minimumScaleFactor(0.8)
            }
            .padding(TMISpacing.sm)
            .frame(maxWidth: .infinity)
            .background(isSelected ? modelColor.opacity(0.1) : Color.tmiBackground)
            .cornerRadius(TMIRadius.sm)
            .overlay(
                RoundedRectangle(cornerRadius: TMIRadius.sm)
                    .stroke(isSelected ? modelColor : Color.clear, lineWidth: 2)
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel("\(model.rawValue)\(isSelected ? ", selected" : "")")
    }

    // MARK: - Students Content

    private var studentsContent: some View {
        VStack(alignment: .leading, spacing: TMISpacing.md) {
            if selectedStudents.isEmpty {
                Text("No students added yet.")
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextSecondary)
            } else {
                ForEach(selectedStudents) { student in
                    HStack(spacing: TMISpacing.md) {
                        TMIAvatar(
                            initials: student.initials,
                            color: .tmiPrimary,
                            size: 36
                        )

                        VStack(alignment: .leading, spacing: 2) {
                            Text(student.name)
                                .font(.tmiLabelLarge)
                                .foregroundStyle(Color.tmiTextPrimary)
                            Text("Grade \(student.grade)")
                                .font(.tmiCaption)
                                .foregroundStyle(Color.tmiTextSecondary)
                        }

                        Spacer()

                        Button {
                            selectedStudents.removeAll { $0.id == student.id }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .foregroundStyle(Color.tmiError)
                                .font(.system(size: 20))
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("Remove \(student.name)")
                    }
                    .padding(TMISpacing.sm)
                    .background(Color.tmiBackground)
                    .cornerRadius(TMIRadius.sm)
                }
            }

            TMIButton(
                text: "Add Student",
                icon: "person.badge.plus",
                style: .secondary,
                action: { showStudentPicker = true }
            )
        }
    }

    // MARK: - Goals Content

    private var goalsContent: some View {
        VStack(alignment: .leading, spacing: TMISpacing.md) {
            if goals.isEmpty {
                Text("No goals added yet.")
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextSecondary)
            } else {
                ForEach(goals) { goal in
                    goalRow(goal)
                }
            }

            TMIButton(
                text: "Add Goal",
                icon: "plus.circle",
                style: .secondary,
                action: { showAddGoal = true }
            )

            Divider()

            fieldGroup(label: "Notes") {
                TextEditor(text: $notes)
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextPrimary)
                    .frame(minHeight: 80)
                    .padding(TMISpacing.sm)
                    .background(Color.tmiBackground)
                    .cornerRadius(TMIRadius.sm)
            }
        }
    }

    private func goalRow(_ goal: Goal) -> some View {
        HStack(alignment: .top, spacing: TMISpacing.md) {
            Image(systemName: goalStatusIcon(goal.status))
                .foregroundStyle(goalStatusColor(goal.status))
                .font(.system(size: 18))
                .padding(.top, 2)

            VStack(alignment: .leading, spacing: 4) {
                Text(goal.description)
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextPrimary)

                HStack(spacing: TMISpacing.sm) {
                    Text(goal.status.rawValue)
                        .font(.tmiCaption)
                        .foregroundStyle(goalStatusColor(goal.status))

                    if let dueDate = goal.dueDate {
                        Text("Due \(dueDate.formatted(date: .abbreviated, time: .omitted))")
                            .font(.tmiCaption)
                            .foregroundStyle(Color.tmiTextSecondary)
                    }
                }

                ProgressView(value: goal.progress)
                    .tint(goalStatusColor(goal.status))
            }

            Spacer()

            Button {
                goals.removeAll { $0.id == goal.id }
            } label: {
                Image(systemName: "trash")
                    .foregroundStyle(Color.tmiError)
                    .font(.system(size: 14))
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Delete goal")
        }
        .padding(TMISpacing.sm)
        .background(Color.tmiBackground)
        .cornerRadius(TMIRadius.sm)
    }

    // MARK: - Approval Content

    private var approvalContent: some View {
        VStack(alignment: .leading, spacing: TMISpacing.md) {
            // Current status
            HStack(spacing: TMISpacing.sm) {
                Image(systemName: approvalStatus.icon)
                    .foregroundStyle(approvalStatusColor(approvalStatus))

                Text(approvalStatus.displayName)
                    .font(.tmiLabelLarge)
                    .foregroundStyle(approvalStatusColor(approvalStatus))

                Spacer()
            }
            .padding(TMISpacing.md)
            .background(approvalStatusColor(approvalStatus).opacity(0.1))
            .cornerRadius(TMIRadius.sm)

            // Rejection reason
            if let rejectionReason = existingPlan?.rejectionReason, !rejectionReason.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Rejection Reason")
                        .font(.tmiCaption)
                        .foregroundStyle(Color.tmiTextSecondary)
                    Text(rejectionReason)
                        .font(.tmiBody)
                        .foregroundStyle(Color.tmiTextPrimary)
                }
                .padding(TMISpacing.md)
                .background(Color.tmiError.opacity(0.08))
                .cornerRadius(TMIRadius.sm)
            }

            // Submit button
            if approvalStatus == .draft || approvalStatus == .changesRequested {
                TMIButton(
                    text: "Submit for Approval",
                    icon: "paperplane.fill",
                    style: .primary,
                    isDisabled: !isValid || !isEditMode,
                    action: submitForApproval
                )

                if !isEditMode {
                    Text("Save the plan first to enable approval submission.")
                        .font(.tmiCaption)
                        .foregroundStyle(Color.tmiTextSecondary)
                }
            }

            // Approval history
            if !approvalHistory.isEmpty {
                Divider()

                Text("History")
                    .font(.tmiCaption)
                    .foregroundStyle(Color.tmiTextSecondary)

                ForEach(approvalHistory, id: \.timestamp) { entry in
                    HStack(alignment: .top, spacing: TMISpacing.sm) {
                        Circle()
                            .fill(Color.tmiTextTertiary)
                            .frame(width: 8, height: 8)
                            .padding(.top, 6)

                        VStack(alignment: .leading, spacing: 2) {
                            Text(entry.action.displayName)
                                .font(.tmiBody)
                                .foregroundStyle(Color.tmiTextPrimary)

                            Text(entry.timestamp.formatted(date: .abbreviated, time: .shortened))
                                .font(.tmiCaption)
                                .foregroundStyle(Color.tmiTextSecondary)

                            if let comment = entry.comment, !comment.isEmpty {
                                Text(comment)
                                    .font(.tmiCaption)
                                    .foregroundStyle(Color.tmiTextSecondary)
                                    .italic()
                            }
                        }
                    }
                }
            }
        }
    }

    // MARK: - Advanced Planning

    private var advancedPlanningCard: some View {
        sectionCard {
            VStack(alignment: .leading, spacing: TMISpacing.sm) {
                Button {
                    withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
                        advancedSectionsExpanded.toggle()
                    }
                } label: {
                    HStack(spacing: TMISpacing.sm) {
                        Image(systemName: "ellipsis.circle")
                            .foregroundStyle(Color.tmiTextSecondary)

                        VStack(alignment: .leading, spacing: 4) {
                            Text("More Planning Options")
                                .font(.tmiLabelLarge)
                                .foregroundStyle(Color.tmiTextPrimary)

                            Text("Career pathways, forms, goals, and approval are available when you need more detail.")
                                .font(.tmiCaption)
                                .foregroundStyle(Color.tmiTextSecondary)
                                .multilineTextAlignment(.leading)
                        }

                        Spacer()

                        Image(systemName: advancedSectionsExpanded ? "chevron.up" : "chevron.down")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(Color.tmiTextSecondary)
                    }
                }
                .buttonStyle(.plain)
            }
            .padding(TMISpacing.md)
        }
    }

    // MARK: - Bottom Save Bar

    private var bottomSaveBar: some View {
        VStack {
            Spacer()

            VStack(alignment: .leading, spacing: TMISpacing.md) {
                fieldGroup(label: "Student Next Step") {
                    TextField(
                        "What should the student do next?",
                        text: $studentNextStep,
                        axis: .vertical
                    )
                    .lineLimit(2...4)
                    .font(.tmiBody)
                    .foregroundStyle(Color.tmiTextPrimary)
                    .padding(TMISpacing.md)
                    .background(Color.tmiSurface)
                    .cornerRadius(TMIRadius.sm)
                }

                Text("Required before saving so the student leaves with one clear next action.")
                    .font(.tmiCaption)
                    .foregroundStyle(Color.tmiTextSecondary)

                HStack(spacing: TMISpacing.md) {
                    TMIButton(
                        text: "Cancel",
                        style: .secondary,
                        action: { dismiss() }
                    )

                    TMIButton(
                        text: isEditMode ? "Save Changes" : "Create Plan",
                        icon: "checkmark",
                        style: .primary,
                        isLoading: isSaving,
                        isDisabled: !isValid,
                        action: savePlan
                    )
                }
            }
            .padding(TMISpacing.md)
            .background(
                Color.tmiBackground
                    .shadow(color: .black.opacity(0.1), radius: 8, y: -2)
            )
        }
    }

    // MARK: - Student Picker Sheet

    private var studentPickerSheet: some View {
        NavigationStack {
            Group {
                if isLoadingStudents {
                    ProgressView("Loading students…")
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if availableStudents.isEmpty {
                    ContentUnavailableView(
                        "No Students Found",
                        systemImage: "person.slash",
                        description: Text("Add students to your roster first.")
                    )
                } else {
                    List(availableStudents) { student in
                        let isAlreadySelected = selectedStudents.contains { $0.id == student.id }
                        Button {
                            if isAlreadySelected {
                                selectedStudents.removeAll { $0.id == student.id }
                            } else {
                                selectedStudents.append(student)
                            }
                        } label: {
                            HStack {
                                TMIAvatar(initials: student.initials, color: .tmiPrimary, size: 36)

                                VStack(alignment: .leading, spacing: 2) {
                                    Text(student.name)
                                        .font(.tmiLabelLarge)
                                        .foregroundStyle(Color.tmiTextPrimary)
                                    Text("Grade \(student.grade)")
                                        .font(.tmiCaption)
                                        .foregroundStyle(Color.tmiTextSecondary)
                                }

                                Spacer()

                                if isAlreadySelected {
                                    Image(systemName: "checkmark.circle.fill")
                                        .foregroundStyle(Color.tmiPrimary)
                                }
                            }
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
            .navigationTitle("Select Students")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { showStudentPicker = false }
                        .fontWeight(.semibold)
                }
            }
        }
    }

    // MARK: - Add Goal Sheet

    private var addGoalSheet: some View {
        NavigationStack {
            Form {
                Section("Goal Description") {
                    TextField(
                        "Describe the goal",
                        text: $newGoalDescription,
                        axis: .vertical
                    )
                    .lineLimit(3...6)
                }

                Section {
                    Toggle("Set Due Date", isOn: $newGoalHasDueDate)

                    if newGoalHasDueDate {
                        DatePicker(
                            "Due Date",
                            selection: Binding(
                                get: { newGoalDueDate ?? Date() },
                                set: { newGoalDueDate = $0 }
                            ),
                            in: Date()...,
                            displayedComponents: .date
                        )
                    }
                }
            }
            .padding(.horizontal)
            .navigationTitle("Add Goal")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Cancel") {
                        resetGoalForm()
                        showAddGoal = false
                    }
                }

                ToolbarItem(placement: .topBarTrailing) {
                    Button("Add") {
                        commitNewGoal()
                        showAddGoal = false
                    }
                    .fontWeight(.semibold)
                    .disabled(newGoalDescription.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
    }

    // MARK: - Helper view

    @ViewBuilder
    private func fieldGroup<C: View>(label: String, @ViewBuilder _ field: () -> C) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(label)
                .font(.tmiCaption)
                .foregroundStyle(Color.tmiTextSecondary)
            field()
        }
    }

    // MARK: - Data Loading

    @MainActor
    private func loadAvailableStudents() async {
        isLoadingStudents = true
        defer { isLoadingStudents = false }

        do {
            availableStudents = try await studentService.fetchStudents()
        } catch {
            print("[TMIPlanEditorView] Error loading students: \(error.localizedDescription)")
            availableStudents = []
        }
    }

    // MARK: - Field Population

    private func populateFields() {
        if let plan = existingPlan {
            // Edit mode — restore all fields from the existing plan
            planTitle = plan.title
            planDescription = plan.description ?? ""
            selectedModel = plan.model
            selectedStudents = plan.students
            linkedInterests = plan.interests
            linkedResources = plan.resources
            goals = plan.goals
            let savedNotes = Self.extractStudentNextStep(from: plan.notes)
            studentNextStep = savedNotes.nextStep
            notes = savedNotes.notes
            startDate = plan.startDate
            endDate = plan.endDate
            hasEndDate = plan.endDate != nil
            approvalStatus = plan.approvalStatus
            approvalHistory = plan.approvalHistory

            studentsExpanded = plan.students.isEmpty
        } else {
            // Create mode — apply preselected student and default title
            if let student = preselectedStudent {
                selectedStudents = [student]
            } else {
                studentsExpanded = true
            }
            planTitle = autoGeneratedTitle
            approvalStatus = .draft
        }
    }

    // MARK: - Title Auto-generation

    private func autoUpdateTitle() {
        guard !isEditMode else { return }
        let trimmedTitle = planTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        let matchesAnyModel = TMIPlanModel.allCases.contains { trimmedTitle.hasPrefix($0.rawValue) }
        if trimmedTitle.isEmpty || matchesAnyModel {
            planTitle = autoGeneratedTitle
        }
    }

    // MARK: - Goal Actions

    private func commitNewGoal() {
        let trimmed = newGoalDescription.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let goal = Goal(
            description: trimmed,
            dueDate: newGoalHasDueDate ? newGoalDueDate : nil,
            status: .notStarted,
            progress: 0.0
        )
        goals.append(goal)
        resetGoalForm()
    }

    private func resetGoalForm() {
        newGoalDescription = ""
        newGoalDueDate = nil
        newGoalHasDueDate = false
    }

    // MARK: - Save Plan

    private func savePlan() {
        guard isValid else { return }

        Task {
            await MainActor.run {
                isSaving = true
                errorMessage = nil
            }

            do {
                let uid = Auth.auth().currentUser?.uid ?? ""
                let trimmedTitle = planTitle.trimmingCharacters(in: .whitespacesAndNewlines)
                let trimmedDescription = planDescription.trimmingCharacters(in: .whitespacesAndNewlines)
                let combinedNotes = Self.notes(
                    withStudentNextStep: trimmedStudentNextStep,
                    notes: notes
                )

                if var plan = existingPlan {
                    plan.title = trimmedTitle
                    plan.description = trimmedDescription.isEmpty ? nil : trimmedDescription
                    plan.model = selectedModel
                    plan.students = selectedStudents
                    plan.interests = linkedInterests
                    plan.resources = linkedResources
                    plan.goals = goals
                    plan.notes = combinedNotes
                    plan.startDate = startDate
                    plan.endDate = hasEndDate ? endDate : nil
                    plan.lastUpdated = Date()

                    let updated = try await planService.updatePlan(plan)
                    await MainActor.run {
                        isSaving = false
                        onSaved?(updated)
                        dismiss()
                    }
                } else {
                    let newPlan = TMIPlan(
                        title: trimmedTitle,
                        description: trimmedDescription.isEmpty ? nil : trimmedDescription,
                        students: selectedStudents,
                        model: selectedModel,
                        interests: linkedInterests,
                        startDate: startDate,
                        endDate: hasEndDate ? endDate : nil,
                        creationDate: Date(),
                        lastUpdated: Date(),
                        goals: goals,
                        progress: 0.0,
                        notes: combinedNotes,
                        createdBy: uid,
                        resources: linkedResources,
                        approvalStatus: .draft,
                        approvalHistory: []
                    )

                    let created = try await planService.addPlan(newPlan)
                    await MainActor.run {
                        isSaving = false
                        onSaved?(created)
                        onPlanCreated?()
                        dismiss()
                    }
                }
            } catch {
                await MainActor.run {
                    isSaving = false
                    errorMessage = "Failed to save plan: \(error.localizedDescription)"
                }
            }
        }
    }

    // MARK: - Submit for Approval

    private func submitForApproval() {
        guard isEditMode, var plan = existingPlan else { return }

        Task {
            await MainActor.run {
                isSaving = true
                errorMessage = nil
            }

            do {
                let uid = Auth.auth().currentUser?.uid ?? ""
                plan.approvalStatus = .pendingApproval
                plan.submittedForApprovalAt = Date()
                plan.submittedBy = uid
                plan.approvalHistory.append(
                    ApprovalHistoryEntry(action: .submitted, actionBy: uid)
                )

                let updated = try await planService.updatePlan(plan)
                await MainActor.run {
                    approvalStatus = .pendingApproval
                    approvalHistory = updated.approvalHistory
                    isSaving = false
                }
            } catch {
                await MainActor.run {
                    isSaving = false
                    errorMessage = "Failed to submit for approval: \(error.localizedDescription)"
                }
            }
        }
    }

    // MARK: - Color / Icon Helpers

    private func approvalStatusColor(_ status: PlanApprovalStatus) -> Color {
        switch status {
        case .draft: return .gray
        case .pendingApproval: return .orange
        case .approved: return .green
        case .rejected: return .red
        case .changesRequested: return .yellow
        }
    }

    private func goalStatusIcon(_ status: GoalStatus) -> String {
        switch status {
        case .notStarted: return "circle"
        case .inProgress: return "circle.bottomhalf.filled"
        case .completed: return "checkmark.circle.fill"
        }
    }

    private func goalStatusColor(_ status: GoalStatus) -> Color {
        switch status {
        case .notStarted: return .gray
        case .inProgress: return .blue
        case .completed: return .green
        }
    }

    private func colorForModel(_ model: TMIPlanModel) -> Color {
        switch model {
        case .chaseYourSpace: return .blue
        case .acknowledgeInterests: return .pink
        case .alignYourMind: return .purple
        case .directAndCorrect: return .orange
        case .bullyToBoss: return .red
        case .meekToProtector: return .green
        }
    }

    private func iconForModel(_ model: TMIPlanModel) -> String {
        switch model {
        case .chaseYourSpace: return "airplane.departure"
        case .acknowledgeInterests: return "heart.fill"
        case .alignYourMind: return "brain.head.profile"
        case .directAndCorrect: return "arrow.up.forward.circle.fill"
        case .bullyToBoss: return "person.fill.badge.plus"
        case .meekToProtector: return "shield.lefthalf.filled"
        }
    }

    static func defaultPlanTitle(for model: TMIPlanModel, students: [Student]) -> String {
        let primaryStudentName = students
            .sorted { lhs, rhs in
                let nameComparison = lhs.name.localizedStandardCompare(rhs.name)
                if nameComparison != .orderedSame {
                    return nameComparison == .orderedAscending
                }

                let leftIdentifier = lhs.id ?? ""
                let rightIdentifier = rhs.id ?? ""
                return leftIdentifier.localizedStandardCompare(rightIdentifier) == .orderedAscending
            }
            .first?
            .name
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""

        return primaryStudentName.isEmpty ? model.rawValue : "\(model.rawValue) - \(primaryStudentName)"
    }

    private static func notes(withStudentNextStep nextStep: String, notes: String) -> String {
        let trimmedNextStep = nextStep.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedNotes = notes.trimmingCharacters(in: .whitespacesAndNewlines)

        guard !trimmedNextStep.isEmpty else {
            return trimmedNotes
        }

        if trimmedNotes.isEmpty {
            return "Student Next Step: \(trimmedNextStep)"
        }

        return """
        Student Next Step: \(trimmedNextStep)

        \(trimmedNotes)
        """
    }

    private static func extractStudentNextStep(from storedNotes: String) -> (nextStep: String, notes: String) {
        let lines = storedNotes.components(separatedBy: .newlines)

        guard let nextStepIndex = lines.firstIndex(where: { $0.hasPrefix("Student Next Step:") }) else {
            return ("", storedNotes)
        }

        let nextStepLine = lines[nextStepIndex]
        let nextStep = nextStepLine
            .replacingOccurrences(of: "Student Next Step:", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        var remainingLines = lines
        remainingLines.remove(at: nextStepIndex)
        let remainingNotes = remainingLines
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        return (nextStep, remainingNotes)
    }
}

// MARK: - Previews

#Preview("Create (no student)") {
    NavigationStack {
        TMIPlanEditorView()
    }
}

#Preview("Create with Preselected Student") {
    NavigationStack {
        TMIPlanEditorView(preselectedStudent: Student.sampleStudent)
    }
}

#Preview("Edit Existing Plan") {
    NavigationStack {
        TMIPlanEditorView(existingPlan: TMIPlan.samplePlan)
    }
}
